version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-service
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cloud_tp
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin1234
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      - my-network

networks:
  my-network:
    name: cloud-tp-network