version: '3.8'

services:
  apache-php:
    build: . 
    container_name: apache-php
    ports:
      - "8080:80" # Map port 80 of the container to port 8080 on the host
    volumes:
      - ./web:/var/www/html # Mount your web files into the container

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306" # Map port 3306 for MySQL
    environment:
      MYSQL_ROOT_PASSWORD: R@@t_passw0rd
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./web/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
