# apache/docker-compose.yml
version: '3.8'

services:
  webserver:
    build: .
    container_name: php_apache
    ports:
      - "8080:80"
    volumes:
      - ./web:/var/www/html
    networks:
      - app_network

networks:
  app_network:
    external: true